postprocessor_pipeline:
    # Duplicate layer.
  - name: duplicate_elevation
    type: gridMapFilters/DuplicationFilter
    params:
      input_layer: elevation
      output_layer: z_temp

  - name: duplicate_z_temp
    type: gridMapFilters/DuplicationFilter
    params:
      input_layer: z_temp
      output_layer: z_finite

  # Fill holes in the map with inpainting.
  - name: inpaint
    type: gridMapCv/InpaintFilter
    params:
      input_layer: z_temp
      output_layer: z_inpainted
      radius: 0.4

  - name: duplicate_z
    type: gridMapFilters/DuplicationFilter
    params:
      input_layer: z_inpainted
      output_layer: z

  # Reduce noise with a radial blurring filter.
  - name: mean_in_radius
    type: gridMapFilters/MeanInRadiusFilter
    params:
      input_layer: z_inpainted
      output_layer: z_smooth
      radius: 0.2

  # Compute surface normals.
  - name: surface_normals
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: z_inpainted
      output_layers_prefix: normal_vectors_
      radius: 0.15
      normal_vector_positive_axis: z

  # Compute smooth surface normals.
  - name: smooth_surface_normals
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: z_smooth
      output_layers_prefix: smooth_normal_vectors_
      radius: 0.4
      normal_vector_positive_axis: z

  # Compute slope from surface normal.
  - name: slope
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: slope
      expression: acos(normal_vectors_z)

  # Compute roughness as absolute difference from map to smoothened map.
  - name: roughness
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: roughness
      expression: abs(z_inpainted - z_smooth)

  # Set lower threshold on traversability.
  - name: z_finite_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      condition_layer: z
      output_layer: z_finite
      lower_threshold: -1000.0
      set_to: -1000.0

  # Compute a hole mask as the difference between the raw and inpainted height
  - name: traversability_hole_mask
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: traversability_hole_mask
      expression: (1.0 - abs(z_finite - z_inpainted))

  # Filter the hole mask to add a barrier radius
  - name: traversability_filter
    type: gridMapFilters/MeanInRadiusFilter
    params:
      input_layer: traversability_hole_mask
      output_layer: traversability_hole_mask_filtered
      radius: 0.075

    # Set lower threshold on traversability hole mask.
  - name: traversability_hole_mask_lower_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      condition_layer: traversability_hole_mask_filtered
      output_layer: traversability_hole_mask_filtered
      lower_threshold: 0
      set_to: 0

  # Compute traversability as normalized weighted sum of slope and roughness
  - name: traversability
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: traversability
      expression: ( 0.5 * (1.0 - (roughness / 0.1)) +
                    0.5 * (1.0 - (slope / 0.4) ) )
                    
  # Set lower threshold on traversability.
  - name: traversability_lower_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      condition_layer: traversability
      output_layer: traversability
      lower_threshold: 0.0
      set_to: 0.0

  # Add hole mask to traversability, add epsilon to any non-hole features
  - name: traversability_apply_hole_mask
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: traversability
      expression: (traversability + 2e-2) .* traversability_hole_mask_filtered

    # Set upper threshold on traversability.
  - name: traversability_upper_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      condition_layer: traversability
      output_layer: traversability
      upper_threshold: 1.0
      set_to: 1.0 # Other uses: .nan, .inf

  # Delete layers.
  - name: delete
    type: gridMapFilters/DeletionFilter
    params:
      layers: [z_temp, z_finite, traversability_hole_mask, traversability_hole_mask_filtered, elevation, variance, horizontal_variance_x, horizontal_variance_y, horizontal_variance_xy, color, time, dynamic_time, lowest_scan_point, sensor_x_at_lowest_scan, sensor_y_at_lowest_scan, sensor_z_at_lowest_scan, slope, roughness]